// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/uidgen/uidgen.go

// Package mock_uidgen is a generated GoMock package.
package mock_ports

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUIDGen is a mock of UIDGen interface.
type MockUIDGen struct {
	ctrl     *gomock.Controller
	recorder *MockUIDGenMockRecorder
}

// MockUIDGenMockRecorder is the mock recorder for MockUIDGen.
type MockUIDGenMockRecorder struct {
	mock *MockUIDGen
}

// NewMockUIDGen creates a new mock instance.
func NewMockUIDGen(ctrl *gomock.Controller) *MockUIDGen {
	mock := &MockUIDGen{ctrl: ctrl}
	mock.recorder = &MockUIDGenMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUIDGen) EXPECT() *MockUIDGenMockRecorder {
	return m.recorder
}

// NewUuid mocks base method.
func (m *MockUIDGen) NewUuid() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewUuid")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewUuid indicates an expected call of NewUuid.
func (mr *MockUIDGenMockRecorder) NewUuid() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewUuid", reflect.TypeOf((*MockUIDGen)(nil).NewUuid))
}
